--CREATE SEQUENCE serial START 100;
--SELECT nextval('serial');

--INSERT INTO METHOD (ID, NAME) VALUES ( 1, 'Traditional 2.0');
--INSERT INTO METHOD (ID, NAME) VALUES ( 2, 'Agile');

INSERT INTO METHOD (NAME) VALUES ( 'Traditional 2.0');
INSERT INTO METHOD (NAME) VALUES (  'Agile');



--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(nextval('serial'),'WaterFall','1');
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(nextval('serial'),'Projet Developpement','1');
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(nextval('serial'),'Projet Etude','1');
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(nextval('serial'),'Processus Iteratif','2');
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(nextval('serial'),'Produit Agile','2');

--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(1,'WaterFall',1);
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(2,'Projet Developpement',1);
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(3,'Projet Etude',1);
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(4,'Processus Iteratif',2);
--INSERT INTO  METHOD_MAPPING (ID, NAME,METHOD_ID)  VALUES(5,'Produit Agile',2);

INSERT INTO  METHOD_MAPPING (NAME,METHOD_ID)  VALUES('WaterFall',1);
INSERT INTO  METHOD_MAPPING ( NAME,METHOD_ID)  VALUES('Projet Developpement',1);
INSERT INTO  METHOD_MAPPING ( NAME,METHOD_ID)  VALUES('Projet Etude',1);
INSERT INTO  METHOD_MAPPING (NAME,METHOD_ID)  VALUES('Processus Iteratif',2);
INSERT INTO  METHOD_MAPPING ( NAME,METHOD_ID)  VALUES('Produit Agile',2);


--INSERT INTO PROCESS(ID, DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES (1, 'Processus de Validation Architecture', 'STANDARD','ARCHITECTURE','10001');
--
--INSERT INTO PROCESS(ID, DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES (2, 'Processus de Validation Architecture Allegée', 'LIGHT','ARCHITECTURE','10001');
--
--INSERT INTO PROCESS(ID, DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES (3, 'Processus de Validation Architecture Rapprochée', 'ENFORCED','ARCHITECTURE','10001');
--
--INSERT INTO PROCESS(ID, DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ('10004', 'Processus de Validation Architecture', 'STANDARD','ARCHITECTURE','10002');
--
--INSERT INTO PROCESS(ID, DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ('10005', 'Processus de Validation Architecture Allegée', 'LIGHT','ARCHITECTURE','10002');
--INSERT INTO PROCESS(ID, DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ('10006', 'Processus de Validation Architecture Rapprochée', 'ENFORCED','ARCHITECTURE','10002');

INSERT INTO PROCESS(  DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ( 'Processus de Validation Architecture', 'STANDARD','ARCHITECTURE',1);
INSERT INTO PROCESS(  DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ( 'Processus de Validation Architecture Allegée', 'LIGHT','ARCHITECTURE',1);
INSERT INTO PROCESS(  DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ( 'Processus de Validation Architecture Rapprochée', 'ENFORCED','ARCHITECTURE',1);
INSERT INTO PROCESS(  DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ( 'Processus de Validation Architecture', 'STANDARD','ARCHITECTURE',2);
INSERT INTO PROCESS(  DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ( 'Processus de Validation Architecture Allegée', 'LIGHT','ARCHITECTURE',2);
INSERT INTO PROCESS( DISPLAY_NAME,FOLLOW_UP, PROCESS_TYPE,METHOD_ID)  VALUES ( 'Processus de Validation Architecture Rapprochée', 'ENFORCED','ARCHITECTURE',2);



--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10001','Realiser Comite de Lecture','10001');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10002','Realiser Comite de Lecture','10002');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10003','Realiser Comite de Lecture','10003');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10004','Realiser Comite de Lecture','10004');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10005','Realiser Comite de Lecture','10005');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10006','Realiser Comite de Lecture','10006');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10007','Passer en CAM','10001');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10008','Passer en CAM','10003');
--INSERT INTO PROCESS_ACTIVITY(ID, NAME , PROCESS_ID) VALUES('10009','Passer en CAM','10006');


INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Realiser Comite de Lecture',1);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Realiser Comite de Lecture',2);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Realiser Comite de Lecture',3);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Realiser Comite de Lecture',4);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Realiser Comite de Lecture',5);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Realiser Comite de Lecture',6);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Passer en CAM',1);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Passer en CAM',3);
INSERT INTO PROCESS_ACTIVITY(  NAME , PROCESS_ID) VALUES( 'Passer en CAM',6);

--INSERT INTO ARTIFACT(ID,NAME,TAG)  VALUES('10001','Dossier Architecture','Dos_Arch');
--INSERT INTO ARTIFACT(ID,NAME,TAG)  VALUES('10002','Fiche de Sécurité','Fic_Sec');
--INSERT INTO ARTIFACT(ID,NAME,TAG)  VALUES('10003','Revue Architecture','Rev_Arch');
--INSERT INTO ARTIFACT(ID,NAME,TAG)  VALUES('10004','Revue Sécurité','Rev_Sec');
--INSERT INTO ARTIFACT(ID,NAME,TAG)  VALUES('10005','Revue Preparation','Rev_Prep');

INSERT INTO ARTIFACT( NAME,TAG)  VALUES( 'Dossier Architecture','Dos_Arch');
INSERT INTO ARTIFACT( NAME,TAG)  VALUES('Fiche de Sécurité','Fic_Sec');
INSERT INTO ARTIFACT( NAME,TAG)  VALUES('Revue Architecture','Rev_Arch');
INSERT INTO ARTIFACT( NAME,TAG)  VALUES('Revue Sécurité','Rev_Sec');
INSERT INTO ARTIFACT( NAME,TAG)  VALUES('Revue Preparation','Rev_Prep');

INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(1,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(2,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(3,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(4,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(5,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(6,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(7,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(8,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(9,1);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(7,5);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(8,5);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(9,5);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(7,3);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(8,3);
INSERT INTO  ACTIVITY_HAS_ARTIFACT(PROCESS_ACTIVITY_ID,ARTIFACT_ID) VALUES(9,3);









